name: Update README

on:
  schedule:
   - cron: '0 0 * * *'
  push:
    branches:
      - main  # Ganti dengan nama branch Anda jika berbeda
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ganti dengan versi Node.js yang Anda inginkan

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Update Script
        run: |
          node updateReadme.js

      - name: Commit Changes
        run: |
          git config --local user.email "nadivaaanggraini@gmail.com"
          git config --local user.name "nadiva-anggraini"
          git add README.md
          git commit -m "Update" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push origin main  # Ganti dengan nama branch Anda jika berbeda
